const IMAGE_SCALE = 0.15;
const IMAGE_HEIGHT = 470;
const IMAGE_WIDTH = 270;
const SCALED_HEIGHT = IMAGE_SCALE * IMAGE_HEIGHT;
const SCALED_WIDTH = IMAGE_SCALE * IMAGE_WIDTH;

const CANVAS_HEIGHT = 900;
const CANVAS_WIDTH = 500;

export const GAME_CONSTANTS = {
  IMAGE_SCALE,
  IMAGE_HEIGHT,
  IMAGE_WIDTH,
  SCALED_HEIGHT,
  SCALED_WIDTH,
};

export { CANVAS_HEIGHT, CANVAS_WIDTH };
